config/routes.rb
Rails.application.routes.draw do
  root "video_games#index"

  devise_for :users

  resources :video_games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :video_games
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  before_action :set_video_game, only: [:show, :edit, :update, :destroy]
 
  def index
    @video_games = current_user.video_games
  end

  def show
  end

  def new
    @video_game = VideoGame.new
  end

  def create
    @video_game = current_user.video_games.new(video_game_params)
    if @video_game.save
      redirect_to video_games_path
    else
      video_game :new
    end
  end

  def edit
  end

  def update
    if @video_game.update(video_game_params)
      redirect_to video_game_path(@video_game)
    else
      render :edit
    end
  end

  def destroy
    @video_game.destroy
    redirect_to video_games_path
  end

  private
    def video_game_params
      params.require(:video_game).permit(:name)
    end

    def set_video_game
      @video_game = current_user.video_games.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGamesLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/video_games/_form.html.erb
<h1><%= @video_game.id ? 'Edit Video Game' : 'Create Video Game' %></h1>
<hr />
<%=  form_for [@user, @video_game] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/video_games/edit.html.erb
<h3>Edit Video Game</h3>

<%= render "form", video_game: @video_game %>

<%= link_to "Show", video_game_path(@video_game) %>
<%= link_to "Back", video_games_path %>

app/views/video_games/index.html.erb
<%= button_to "Logout", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to "Add Video Game", new_video_game_path %>
<h3>Your Video Games</h3>
<ul>
  <% @video_games.each do |video_game| %>
    <li>
      <%= link_to video_game.name, video_game_path(video_game) %>
    </li>
  <% end %>
</ul> 

app/views/video_games/new.html.erb
<h1>Add Video Game</h1>
<%= form_with(model: @video_game, locat: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/video_games/show.html.erb
<h1><%= @video_game.name %></h1>

<%= link_to "Edit Video Game", edit_video_game_path %>
<br />
<%= link_to "Back", video_games_path %>
<br />
<%= button_to "Delete", @video_game, method: :delete %> 